sudo: false
language: node_js
node_js: '0.10'
script:
- travis-lint .travis.yml
- jscs .
- jshint . --exclude-path .gitignore
- make test
- make codeclimate
cache:
  directories:
  - node_modules
env:
  global:
    secure: UYDgGRhmLFBEm+7y6+nZChc8wkfvsgM7wi46WDPdNft+IUKIOyx9pity3SoYA2tmT2Uu1Kt87VMHb4UYuqlTsStewUZZyHsq71XBDf6AdxMNe33zYuH3AWv3DyzN89wXoVnQI0qV+YqoZWvJOZW5KQAXOEC1+YhCv6+Zxh+wBgA=
